workflows:
  ios-release-final:
    name: iOS Release - YOMA
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "YOMA"
        BUNDLE_ID: "com.patriciagiorgetto.yoma.final"
        APPLE_TEAM_ID: "T95384B3A4"
      groups:
        - app_store_credentials
        - signing_credentials
        - firebase_credentials
    scripts:
      - name: Instalar dependências Flutter
        script: |
          flutter pub get

      - name: Limpar build anterior
        script: |
          flutter clean

      - name: Compilar app iOS
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY_CONTENT
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false


  android-release-final:
    name: Android Release - YOMA
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        APP_NAME: "YOMA"
        PACKAGE_NAME: "com.patriciagiorgetto.yoma"
      groups:
        - google_play
        - keystore_credentials
        - firebase_credentials
    scripts:
      - name: Instalar dependências Flutter
        script: |
          flutter pub get

      - name: Limpar build anterior
        script: |
          flutter clean

      - name: Compilar APK e AAB
        script: |
          flutter build appbundle --release
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_JSON
        track: internal
