workflows:
  yoma_release:
    name: YOMA Release Build
    max_build_duration: 60
    environment:
      flutter: "3.32.6"
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "YOMA"
        PACKAGE_NAME: com.patriciagiorgetto.yoma
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk

       publishing:
        app_store_connect:
        apple_id: patriciagiorgetto@hotmail.com
        app_password: $APP_SPECIFIC_PASSWORD
        bundle_id: com.patriciagiorgetto.yoma
        groups:
          - apple_login

  