workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: 3.35.5
      xcode: latest
      vars:
        PACKAGE_NAME: "com.patriciagiorgetto.yoma"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Decode keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > /tmp/keystore.jks
          export CM_KEYSTORE_PATH=/tmp/keystore.jks

      - name: Build Android AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - "seuemail@gmail.com"
