workflows:
  ios_dev_ipa:
    name: iOS Dev IPA
    max_build_duration: 60
    environment:
      sdk: '>=3.8.0 <4.0.0'
      flutter: stable      # ou fixe uma versão que você usa localmente
      xcode: latest
      vars:
        BUNDLE_ID: dominio.yoma.com          # <- tem que bater com o Xcode
        DEVELOPMENT_TEAM_ID: T95384B3A4      # <- seu Team ID
        APP_STORE_CONNECT_ISSUER_ID: 383b2b04-b776-4cc4-8882-ad7107d3b643
        APP_STORE_CONNECT_KEY_IDENTIFIER: 5UA82DPFQR
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          (COLE AQUI O CONTEÚDO .p8 COMPLETO, INCLUINDO BEGIN/END)
          -----END PRIVATE KEY-----
    cache:
      cache_paths:
        - $HOME/.pub-cache

    scripts:
      - name: Debug vars
        script: |
          echo "Team ID: ${DEVELOPMENT_TEAM_ID}"
          echo "Bundle: ${BUNDLE_ID}"

      # 1) Baixa certificado/perfil de desenvolvimento do App Store Connect
      - name: Fetch signing files (Development)
        script: |
          app-store-connect fetch-signing-files \
            "${APP_STORE_CONNECT_ISSUER_ID}" \
            "${APP_STORE_CONNECT_KEY_IDENTIFIER}" \
            "${APP_STORE_CONNECT_PRIVATE_KEY}" \
            --type IOS_APP_DEVELOPMENT \
            --bundle-id "${BUNDLE_ID}" \
            --create

      # 2) Instala certificados no keychain e aplica os perfis ao projeto
      - keychain add-certificates
      - xcode-project use-profiles

      # 3) Archive com assinatura automática e seu TEAM/BUNDLE
      - name: Archive (Xcode)
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM_ID}" \
                     CODE_SIGN_STYLE=Automatic \
                     PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
                     archive

      # 4) Exporta o IPA sem precisar de ExportOptions.plist
      - name: Export IPA (Development)
        script: |
          xcode-project build-ipa \
            --archive-path build/ios/archive/Runner.xcarchive \
            --export-method development \
            --team-id "${DEVELOPMENT_TEAM_ID}"

      # (Opcional) Flutter deps & builds adicionais
      - name: Flutter pub get
        script: flutter pub get
      - name: Build Android AAB
        script: flutter build appbundle --release
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS (no codesign, opcional)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk

    # Publicação (opcional). Se quiser subir para App Store Connect automaticamente:
    #  - use Apple ID + app-specific password OU API Key de Upload do Codemagic.
    publishing:
      app_store_connect:
        apple_id: patriciagiorgetto@hotmail.com
        password: $APP_SPECIFIC_PASSWORD   # defina essa env var segura no Codemagic
