workflows:
  yoma_release:
    name: YOMA Release Build
    max_build_duration: 60
    environment:
      flutter: stable       # ou uma versão fixa, ex: "3.32.6"
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "YOMA"
        PACKAGE_NAME: com.patriciagiorgetto.yoma
      groups:
        - apple_login       # grupo de variáveis seguras do Codemagic
                            # (APP_SPECIFIC_PASSWORD ou API key do App Store Connect)

    cache:
      cache_paths:
        - $HOME/.pub-cache

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build Android AAB
        script: |
          flutter build appbundle --release

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Archive and export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Runner.app

    publishing:
      app_store_connect:
        apple_id: patriciagiorgetto@hotmail.com
        password: $APP_SPECIFIC_PASSWORD   # variável segura criada no Codemagic
