name: yoma_app_novo
description: Aplicativo YOMA final para publicação

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # firebase_core: ^2.32.0
  # cloud_firestore: ^5.0.0
  # flutter_local_notifications: ^16.0.0
  # geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
