workflows:
  yoma_release:
    name: YOMA Release Build
    max_build_duration: 60
    environment:
      flutter: "3.13.9"
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "YOMA"
        PACKAGE_NAME: "com.patriciagiorgetto.yoma"
      groups:
        - app_store_credentials
        - keystore_credentials
    triggering:
      events:
        - push
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
